provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
extraArgs:
  - --source=service # Tells external-dns to only look at Services, ignoring Ingresses/IngressRoutes
  - --annotation-filter=external-dns.custom/managed=true # The opt-in gatekeeper