provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
extraArgs:
  - --source=service
  - --annotation-filter=external-dns.custom/managed=true