apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
spec:
  exporter:
    endpoint: http://opentelemetry-kube-stack-daemon-collector.opentelemetry.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:latest
