alertmanager-ingress:
  enabled: true
  hosts:
    - alertmanager.oikz.dev

grafana:
  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource
  ingress:
    enabled: true
    hosts:
      - grafana.oikz.dev
  persistence:
    type: pvc
    enabled: true