apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
        - name: website
          image: ghcr.io/oikz/website:latest
          env:
            - name: OTEL_TRACES_EXPORTER
              value: 'otlp'
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: 'http/protobuf'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://signoz-otel-collector.signoz.svc.cluster.local:4318'
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: 'deployment.environment=production,service.version=1.0.0'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /WeatherForecast
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
