apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: ghcr.io/oikz/website:6bd61db53f72d9817f383c69ff01c79c2c98438b
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /WeatherForecast
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi