apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
        - name: website
          image: ghcr.io/oikz/website:949a766abe1e53f5a25206c43c9df50ab549393a
          env:
            - name: OTEL_LOGS_EXPORT_URL
              value: http://victoria-logs-single-server.victoria.svc.cluster.local:9428/insert/opentelemetry/v1/logs
            - name: OTEL_TRACES_EXPORT_URL
              value: http://victoria-traces-single-vt-single-server.victoria.svc.cluster.local:10428/insert/opentelemetry/v1/traces
            - name: OTEL_METRICS_EXPORT_URL
              value: http://vmsingle-victoria-metrics-k8s-stack.victoria.svc.cluster.local:8428/opentelemetry/v1/metrics
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /WeatherForecast
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi