apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  template:
    spec:
      containers:
        - name: website
          env:
            - name: NEW_RELIC_APP_NAME
              value: "production-website"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: production-database-app
                  key: host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-database-app
                  key: password