deployment:
  replicas: 1
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.oikz.dev'
globalArguments:
  - "--api.insecure=true"
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: Host(`traefik.oikz.dev`)
    