deployment:
  replicas: 1
globalArguments:
  - "--api.insecure=true"
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: Host(`traefik.oikz.dev`)

service:
  annotations:
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
    oci.oraclecloud.com/load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: "*.oikz.dev"
    external-dns.alpha.kubernetes.io/ttl: "120"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.custom/managed: "true"