apiVersion: newrelic.com/v1beta3
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
  namespace: newrelic
spec:
  agent:
    # Values supported: dotnet, java, nodejs, python, ruby, php
    language: dotnet

    # Values supported: newrelic-java-init:latest, newrelic-dotnet-init:latest, newrelic-node-init:latest, newrelic-python-init:latest, newrelic-ruby-init:latest, newrelic-php-init:latest, newrelic-php-init:musl
    image: docker.io/newrelic/newrelic-dotnet-init:latest

  # Select a namespace with a specific name by using "kubernetes.io/metadata.name" label
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["website"]
  podLabelSelector:
    matchLabels:
      app: production-website
---
apiVersion: newrelic.com/v1beta3
kind: Instrumentation
metadata:
  name: newrelic-instrumentation-stringdicator
  namespace: newrelic
spec:
  agent:
    language: dotnet
    image: docker.io/newrelic/newrelic-dotnet-init:latest

  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["stringdicator"]
  podLabelSelector:
    matchLabels:
      app: stringdicator