apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stringdicator
  name: stringdicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringdicator
  template:
    metadata:
      labels:
        app: stringdicator
    spec:
      initContainers:
        - name: lavalink
          image: ghcr.io/lavalink-devs/lavalink:4
          env:
            - name: _JAVA_OPTIONS
              value: "-Xmx2G"
            - name: SERVER_PORT
              value: "2333"
            - name: LAVALINK_SERVER_PASSWORD
              value: "youshallnotpass"
            - name: LAVALINK_PLUGINS_0_DEPENDENCY
              value: "dev.lavalink.youtube:youtube-plugin:1.18.1"
            - name: LAVALINK_SERVER_SOURCES_YOUTUBE
              value: "false"
            - name: PLUGINS_YOUTUBE_ENABLED
              value: "true"
            - name: PLUGINS_YOUTUBE_ALLOWSEARCH
              value: "true"
            - name: PLUGINS_YOUTUBE_ALLOWDIRECTVIDEOIDS
              value: "true"
            - name: PLUGINS_YOUTUBE_ALLOWDIRECTPLAYLISTIDS
              value: "true"
            - name: PLUGINS_YOUTUBE_CLIENTS_0
              value: "MUSIC"
            - name: PLUGINS_YOUTUBE_CLIENTS_1
              value: "ANDROID"
            - name: PLUGINS_YOUTUBE_CLIENTS_2
              value: "WEB"
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "250m"
          restartPolicy: Always

      containers:
        - name: stringdicator
          image: ghcr.io/oikz/stringdicatorbot/stringdicator:15b13af
          resources:
            requests:
              memory: "500m"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: OTEL_SERVICE_NAME
              value: 'Stringdicator'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-app
                  key: host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-app
                  key: password
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: stringdicator-secrets
                  key: discord-token
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: stringdicator-secrets
                  key: google-api-key
            - name: SEARCH_ENGINE_ID
              valueFrom:
                secretKeyRef:
                  name: stringdicator-secrets
                  key: search-engine-id
            - name: DEV_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: stringdicator-secrets
                  key: dev-guild-id
            - name: DELETED_MESSAGE_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: stringdicator-secrets
                  key: deleted-message-channel-id

      restartPolicy: Always