apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stringdicator
  name: stringdicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringdicator
  template:
    metadata:
      labels:
        app: stringdicator
    spec:
      initContainers:
        - name: lavalink
          image: ghcr.io/lavalink-devs/lavalink:4
          volumeMounts:
            - mountPath: /opt/Lavalink/application.yml
              name: lavalink-application-yaml
              readOnly: true
          env:
            - name: _JAVA_OPTIONS
              value: "-Xmx2G"
            - name: SERVER_PORT
              value: "2333"
            - name: LAVALINK_SERVER_PASSWORD
              value: "youshallnotpass"
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "250m"
          restartPolicy: Always

      containers:
        - name: stringdicator
          image: ghcr.io/oikz/stringdicatorbot/stringdicator:a4603e5
          volumeMounts:
            - mountPath: /app/.env
              name: stringdicator-env
              readOnly: true
          resources:
            requests:
              memory: "500m"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: OTEL_SERVICE_NAME
              value: 'Stringdicator'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-app
                  key: host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-app
                  key: password
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord_token
                  key: token
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: google_api_key
                  key: api_key
            - name: SEARCH_ENGINE_ID
              valueFrom:
                secretKeyRef:
                  name: google_search_engine_id
                  key: search_engine_id
            - name: DEV_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: dev_guild_id
                  key: guild_id
            - name: DELETED_MESSAGE_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: deleted_message_channel_id
                  key: channel_id

      restartPolicy: Always

      volumes:
        - name: lavalink-application-yaml
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/application.yml
            type: File