apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stringdicator
  name: stringdicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringdicator
  template:
    metadata:
      labels:
        app: stringdicator
    spec:
      initContainers:
        - name: lavalink
          image: ghcr.io/lavalink-devs/lavalink:4
          volumeMounts:
            - mountPath: /opt/Lavalink/application.yml
              name: lavalink-application-yaml
              readOnly: true
          #            - mountPath: /opt/Lavalink/plugins/
          #              name: lavalink-plugins
          #              readOnly: true
          env:
            - name: _JAVA_OPTIONS
              value: "-Xmx6G"
            - name: SERVER_PORT
              value: "2333"
            - name: LAVALINK_SERVER_PASSWORD
              value: "youshallnotpass"
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "250m"
          restartPolicy: Always

      containers:
        - name: stringdicator
          image: ghcr.io/oikz/stringdicatorbot/stringdicator:0.1.1
          volumeMounts:
            - mountPath: /app/.env
              name: stringdicator-env
              readOnly: true
            - mountPath: /app/sqlite.db
              name: stringdicator-sqlite
              readOnly: false
            - mountPath: /app/sqlite.db-wal
              name: stringdicator-sqlite-wal
              readOnly: false
            - mountPath: /app/sqlite.db-shm
              name: stringdicator-sqlite-shm
              readOnly: false
          resources:
            requests:
              memory: "4Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "1.0"

      restartPolicy: Always

      volumes:
        - name: lavalink-application-yaml
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/application.yml
            type: File
        - name: lavalink-plugins
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/plugins/
            type: Directory
        - name: stringdicator-env
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/.env
            type: File
        - name: stringdicator-sqlite
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/sqlite.db
            type: File
        - name: stringdicator-sqlite-wal
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/sqlite.db-wal
            type: File
        - name: stringdicator-sqlite-shm
          hostPath:
            path: /home/ubuntu/docker/k8s/stringdicator/sqlite.db-shm
            type: File