global:
  storageClass: local-path

signoz:
  ingress:
    enabled: false
    hosts:
      - host: signoz.oikz.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 8080

clickhouse:
  installCustomStorageClass: true