name: Terraform Apply

on:
  push:
    branches: [ master ]


jobs:
  init:
    name: Init terraform
    runs-on: [ gha-runner-scale-set ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        env:
          OCI_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_user_ocid: ${{ secrets.OCI_USER_OCID }}
          OCI_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          OCI_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_region: ${{ secrets.OCI_REGION }}
        run: terraform init