name: Terraform Apply

on:
  push:
    branches: [ master ]

env:
  OCI_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
  OCI_user_ocid: ${{ secrets.OCI_USER_OCID }}
  OCI_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
  OCI_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
  OCI_region: ${{ secrets.OCI_REGION }}
  TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
  TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
  TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
  TF_VAR_private_key: ${{ secrets.OCI_PRIVATE_KEY }}
  TF_VAR_region: ${{ secrets.OCI_REGION }}

jobs:
  plan:
    name: Terraform plan
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        working-directory: oke
        run: terraform init

      - name: Terraform validate
        working-directory: oke
        run: terraform validate

      - name: Terraform plan
        working-directory: oke
        run: terraform plan -out terraform.plan

      - name: Upload plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          archive: false
          path: oke/terraform.plan


  apply:
    name: Terraform apply
    runs-on: [ ubuntu-latest ]
    environment: apply
    needs: plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: terraform.plan
          path: oke

      - name: Terraform init
        working-directory: oke
        run: terraform init

      - name: Terraform apply
        working-directory: oke
        run: terraform apply terraform.plan